"""display_name not null

Revision ID: 18a3abc4f2dc
Revises: 15f82e159bf6
Create Date: 2026-07-26 14:54:04.060341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18a3abc4f2dc'
down_revision: Union[str, Sequence[str], None] = '15f82e159bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'display_name',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'display_name',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
