"""add description to timeblock

Revision ID: 2bdabb148044
Revises: 507dcab3cd68
Create Date: 2026-07-31 21:12:34.510208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bdabb148044'
down_revision: Union[str, Sequence[str], None] = '507dcab3cd68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_blocks', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_blocks', 'description')
    # ### end Alembic commands ###
