"""user configurable 12h/24h time format

Revision ID: 3b435aff9f7a
Revises: a7756ba2ddf2
Create Date: 2026-08-02 16:44:15.929387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b435aff9f7a'
down_revision: Union[str, Sequence[str], None] = 'a7756ba2ddf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('twelve_hour', 'twenty_four_hour', name='time_format_type').create(op.get_bind())
    op.add_column('user_settings', sa.Column('time_format', postgresql.ENUM('twelve_hour', 'twenty_four_hour', name='time_format_type', create_type=False), server_default='twenty_four_hour', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'time_format')
    sa.Enum('twelve_hour', 'twenty_four_hour', name='time_format_type').drop(op.get_bind())
    # ### end Alembic commands ###
