"""add data conflict handling for notes as well

Revision ID: 5077e23b9ee2
Revises: b6dabd08a03a
Create Date: 2026-07-22 17:41:00.866686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5077e23b9ee2'
down_revision: Union[str, Sequence[str], None] = 'b6dabd08a03a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('version_id', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'version_id')
    # ### end Alembic commands ###
