"""add timeblock model

Revision ID: 507dcab3cd68
Revises: 18a3abc4f2dc
Create Date: 2026-07-27 17:56:15.997491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '507dcab3cd68'
down_revision: Union[str, Sequence[str], None] = '18a3abc4f2dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('category_label', sa.Text(), nullable=True),
    sa.Column('category_color', sa.Text(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint('end_at > start_at', name='ck_time_blocks_end_after_start'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_blocks_task_id'), 'time_blocks', ['task_id'], unique=False)
    op.create_index('ix_time_blocks_user_start', 'time_blocks', ['user_id', 'start_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_time_blocks_user_start', table_name='time_blocks')
    op.drop_index(op.f('ix_time_blocks_task_id'), table_name='time_blocks')
    op.drop_table('time_blocks')
    # ### end Alembic commands ###
