"""replace hardcode strings with enums

Revision ID: 7f9ec64f4826
Revises: 8e7670bfdb7d
Create Date: 2026-07-14 12:02:19.625458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9ec64f4826'
down_revision: Union[str, Sequence[str], None] = '8e7670bfdb7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'energy_tag',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='energytag'),
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'DONE', name='taskstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'DONE', name='taskstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('tasks', 'energy_tag',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='energytag'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
