"""update tasks table

Revision ID: 8e7670bfdb7d
Revises: 4cde484abde3
Create Date: 2026-07-12 21:56:36.034481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e7670bfdb7d'
down_revision: Union[str, Sequence[str], None] = '4cde484abde3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('micro_steps', sa.JSON(), nullable=False))
    op.alter_column('tasks', 'estimate_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'estimate_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tasks', 'micro_steps')
    # ### end Alembic commands ###
