"""add data conflict handling for task updates

Revision ID: b6dabd08a03a
Revises: 245afffdb778
Create Date: 2026-07-22 16:02:53.631150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6dabd08a03a'
down_revision: Union[str, Sequence[str], None] = '245afffdb778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('version_id', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'version_id')
    # ### end Alembic commands ###
