"""replace hardcode strings with enums

Revision ID: c1ffdb534b7d
Revises: 8e7670bfdb7d
Create Date: 2026-07-14 18:20:05.759614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1ffdb534b7d'
down_revision: Union[str, Sequence[str], None] = '8e7670bfdb7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# my additions so that we can use the postgres enum type
energy_tag_enum = postgresql.ENUM(
    "low", "medium", "high",
    name="energy_tag",
    create_type=False,
)
task_status_enum = postgresql.ENUM(
    "not_started", "in_progress", "done",
    name="task_status",
    create_type=False,
)

def upgrade() -> None:
    """Upgrade schema."""
    # my custom commands to add the enums
    energy_tag_enum.create(op.get_bind(), checkfirst=True)
    task_status_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'energy_tag',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('low', 'medium', 'high', name='energy_tag'),
               existing_nullable=True,
               postgresql_using='energy_tag::energy_tag')
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('not_started', 'in_progress', 'done', name='task_status'),
               existing_nullable=False,
               postgresql_using='status::task_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('not_started', 'in_progress', 'done', name='task_status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('tasks', 'energy_tag',
               existing_type=sa.Enum('low', 'medium', 'high', name='energy_tag'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###

    # my custom command to remove the enums
    task_status_enum.drop(op.get_bind(), checkfirst=True)
    energy_tag_enum.drop(op.get_bind(), checkfirst=True)
