"""add categories

Revision ID: f89d864acbb4
Revises: 3b435aff9f7a
Create Date: 2026-08-02 21:26:12.470138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f89d864acbb4'
down_revision: Union[str, Sequence[str], None] = '3b435aff9f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('task', 'time_block', name='category_type').create(op.get_bind())
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=False),
    sa.Column('type', postgresql.ENUM('task', 'time_block', name='category_type', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_categories_user_type', 'categories', ['user_id', 'type'], unique=False)
    op.add_column('tasks', sa.Column('category_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.add_column('time_blocks', sa.Column('category_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'time_blocks', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_column('time_blocks', 'category_color')
    op.drop_column('time_blocks', 'category_label')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_blocks', sa.Column('category_label', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('time_blocks', sa.Column('category_color', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'time_blocks', type_='foreignkey')
    op.drop_column('time_blocks', 'category_id')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'category_id')
    op.drop_index('ix_categories_user_type', table_name='categories')
    op.drop_table('categories')
    sa.Enum('task', 'time_block', name='category_type').drop(op.get_bind())
    # ### end Alembic commands ###
